git clone https://github.com/handreassa/prenotami
cd prenotami
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
mkdir files
echo "username=ADD_USERNAME_HERE" > .env
echo "password=ADD_PASSWORD_HERE" >> .env"
